version: "3.8"

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo
    volumes:
      - mongo-data:/data/db
  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 14268:14268
      - 4318:4318

  auth-api:
    extends:
      file: ./compose/compose.published.yml
      service: auth-api
    depends_on:
      - mariadb

  user-api:
    extends:
      file: ./compose/compose.published.yml
      service: user-api
    depends_on:
      - mariadb
  account-api:
    extends:
      file: ./compose/compose.published.yml
      service: account-api
    depends_on:
      - mariadb

  transaction-api:
    extends:
      file: ./compose/compose.published.yml
      service: transaction-api
    depends_on:
      - mariadb

volumes:
  mongo-data: {}
  mariadb-data: {}

networks:
  default:
    external: true
    name: grpc-bank_default
